backend:
  name: github
  repo: uriivite/avvlacogullada # Path to your GitHub repository
  # optional, defaults to master
  # branch: main

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: about
    label: "Sobre nosaltres"
    folder: "content/about"
    create: false
    format: "toml-frontmatter"
    fields:
      - { label: "Borrador", name: "draft", widget: "boolean" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: contacte
    label: "Contacte"
    folder: "content/contacte"
    create: false
    format: "toml-frontmatter"
    fields:
      - { label: "Borrador", name: "draft", widget: "boolean" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: activitats
    label: "Activitats"
    folder: "content/activitats-fixes"
    create: true
    format: "toml-frontmatter"
    fields:
      - { label: "Borrador", name: "draft", widget: "boolean" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Títol", name: "title", widget: "string" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: esdeveniments
    label: "Esdeveniments"
    folder: "content/esdeveniments"
    create: true
    format: "toml-frontmatter"
    fields:
      - { label: "Borrador", name: "draft", widget: "boolean" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Títol", name: "title", widget: "string" }
      - { label: "Text", name: "body", widget: "markdown" }
