backend:
  name: git-gateway
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: about
    label: "Sobre nosaltres"
    folder: "content/about"
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: "TÃ­tol", name: "title", widget: 'string' }
      - { label: "Text", name: "body", widget: 'markdown' }
      - { label: "Borrador", name: "draft", widget: 'boolean'}
